
def drawMatrices(matrices):
    fig = plt.figure(figsize=(20, 20))
    ax1 = fig.add_subplot(3,3,1)
    ax2 = fig.add_subplot(3,3,2)
    ax3 = fig.add_subplot(3,3,3)
    ax4 = fig.add_subplot(3,3,4)
    ax5 = fig.add_subplot(3,3,5)
    ax6 = fig.add_subplot(3,3,6)
    ax7 = fig.add_subplot(3,3,7)
    ax8 = fig.add_subplot(3,3,8)
    ax1.imshow(matrices[0])
    ax2.imshow(matrices[1])
    ax3.imshow(matrices[2])
    ax4.imshow(matrices[3])
    ax5.imshow(matrices[4])
    ax6.imshow(matrices[5])
    ax7.imshow(matrices[6])
    ax8.imshow(matrices[7])
    ax1.set_title("Ct1")
    ax2.set_title("Ct2")
    ax3.set_title("Rad21")
    ax4.set_title("NIPBL")
    ax5.set_title("CTCF") 
    ax6.set_title("ESCO1")
    ax7.set_title("ESCO2")
    ax8.set_title("ESCO12")

def drawMatrices_line(matrices):
    fig = plt.figure(figsize=(20, 10))
    ax1 = fig.add_subplot(1,7,1)
    ax2 = fig.add_subplot(1,7,2)
    ax3 = fig.add_subplot(1,7,3)
    ax4 = fig.add_subplot(1,7,4)
    ax5 = fig.add_subplot(1,7,5)
    ax6 = fig.add_subplot(1,7,6)
    ax7 = fig.add_subplot(1,7,7)
    ax1.imshow(matrices[0])
    ax2.imshow(matrices[1])
    ax3.imshow(matrices[2])
    ax4.imshow(matrices[3])
    ax5.imshow(matrices[4])
    ax6.imshow(matrices[5])
    ax7.imshow(matrices[6])

def drawMatricesComp(matrices):    
    cm = generate_cmap(['#1310cc', '#FFFFFF', '#d10a3f'])
    fig = plt.figure(figsize=(20, 20))
    ax1 = fig.add_subplot(3,3,1)
    ax2 = fig.add_subplot(3,3,2)
    ax3 = fig.add_subplot(3,3,3)
    ax4 = fig.add_subplot(3,3,4)
    ax5 = fig.add_subplot(3,3,5)
    ax6 = fig.add_subplot(3,3,6)
    ax7 = fig.add_subplot(3,3,7)
    ax1.imshow(matrices[2] - matrices[0], clim=(-3, 3), cmap=cm)
    ax2.imshow(matrices[3] - matrices[0], clim=(-3, 3), cmap=cm)
    ax3.imshow(matrices[4] - matrices[0], clim=(-3, 3), cmap=cm)
    ax4.imshow(matrices[5] - matrices[1], clim=(-3, 3), cmap=cm)
    ax5.imshow(matrices[6] - matrices[1], clim=(-3, 3), cmap=cm)
    ax6.imshow(matrices[7] - matrices[1], clim=(-3, 3), cmap=cm)
    ax7.imshow(matrices[1] - matrices[0], clim=(-3, 3), cmap=cm)
    ax1.set_title("Rad21")
    ax2.set_title("NIPBL")
    ax3.set_title("CTCF") 
    ax4.set_title("ESCO1")
    ax5.set_title("ESCO2")
    ax6.set_title("ESCO12")
    ax7.set_title("Ct")

def drawMatricesComp_line(matrices):
    cm = generate_cmap(['#1310cc', '#FFFFFF', '#d10a3f'])
    fig = plt.figure(figsize=(20, 10))
    ax1 = fig.add_subplot(1,6,1)
    ax2 = fig.add_subplot(1,6,2)
    ax3 = fig.add_subplot(1,6,3)
    ax4 = fig.add_subplot(1,6,4)
    ax5 = fig.add_subplot(1,6,5)
    ax6 = fig.add_subplot(1,6,6)
    ax1.imshow(matrices[2] - matrices[0], clim=(-3, 3), cmap=cm)
    ax2.imshow(matrices[3] - matrices[0], clim=(-3, 3), cmap=cm)
    ax3.imshow(matrices[4] - matrices[0], clim=(-3, 3), cmap=cm)
    ax4.imshow(matrices[5] - matrices[1], clim=(-3, 3), cmap=cm)
    ax5.imshow(matrices[6] - matrices[1], clim=(-3, 3), cmap=cm)
    ax6.imshow(matrices[7] - matrices[1], clim=(-3, 3), cmap=cm)
    
def drawHeatmap_RawandComp(mat1, mat2):
    cm = generate_cmap(['#1310cc', '#FFFFFF', '#d10a3f'])
    fig = plt.figure(figsize=(20, 60))
    ax1 = fig.add_subplot(1,3,1)
    ax2 = fig.add_subplot(1,3,2)
    ax3 = fig.add_subplot(1,3,3)
    ax1.imshow(mat1)
    ax2.imshow(mat2)
    ax3.imshow(mat2 - mat1, clim=(-4, 4), cmap=cm)
